; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Sat Oct 06 2018 22:57:33 GMT-0700 (Mountain Standard Time)
M561 ; clear any bed transform
; Probe the bed at 4 points
G30 P0 X15 Y15 H0 Z-99999
G30 P1 X15 Y220 H0 Z-99999
G30 P2 X220 Y220 H0 Z-99999
G30 P3 X220 Y15 H0 Z-99999 S