; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Sat Oct 06 2018 22:57:33 GMT-0700 (Mountain Standard Time)
M561                ; clear any bed transform
; M98 Pdeployprobe.g  ; deploy mechanical Z probe
; Probe the bed at 5 points
G30 P0 X15 Y15 H0 Z-99999
G30 P1 X15 Y215 H0 Z-99999
G30 P2 X215 Y215 H0 Z-99999
G30 P3 X215 Y15 H0 Z-99999
G30 P4 X107.5 Y107.5 H0 Z-99999 S
; M98 Pretractprobe.g ; retract mechanical Z probe
