; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Sat Oct 20 2018 16:02:39 GMT-0700 (Mountain Standard Time)
; Wait for set temperatures to be reached
M116 P0